@startuml
start
:Работа в Revit;
if (Элементы предварительно выделены?) then (да)
  :Сформировать выделение Revit;
else (нет)
endif
:Открыть ContextFilter;
:Выбрать рабочий контекст;
:Перейти Категория / Семейство / Тип;
:Выбрать параметр и значение;
:Сформировать условия фильтра;
:Получить найденный набор;
if (Сохранить для повторного использования?) then (да)
  :Сохранить полный пресет или шаблон;
endif
:Выбрать действие;
if (Тип действия?) then (Выделение)
  :Заменить / добавить / исключить;
elseif (Видимость)
  :Скрыть / изолировать / инвертировать;
else (Штатный фильтр)
  :Создать совместимый фильтр Revit;
endif
:Продолжить работу в Revit;
stop
@enduml
